apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - name: techtrends
    port: {{ .Values.service.port }}
    protocol: TCP
    {{- if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    {{- else }}
    targetPort: {{ .Values.service.port }}
    {{- end }}
  selector:
    app: techtrends
    tag: lastest
  type: ClusterIP