apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - name: techtrends
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
    tag: lastest
  type: ClusterIP